=== carlosdelval/EjerciciosLMSGI/Examenes resueltos/Examen01.dtd
<!ELEMENT videoclub (peliculas, ofertas)>
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT ofertas (oferta*)>
<!ELEMENT pelicula (nombre, genero, precio, (disponible | alquilada))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT precio EMPTY>
<!ELEMENT disponible EMPTY>
<!ELEMENT alquilada EMPTY>
<!ELEMENT oferta (#PCDATA | peliculasReferidas)*>
<!ELEMENT peliculasReferidas ANY>
<!ATTLIST videoclub direccion CDATA #IMPLIED 
                      nombre CDATA #REQUIRED
                      telefono CDATA #FIXED "957591456">
<!ATTLIST pelicula codigo ID #REQUIRED
                ingredientePrincipal (queso | frijoles | chile) "queso">
<!ATTLIST peliculasReferidas codigoPelicula IDREF #REQUIRED
                        comboPeliculas IDREFS #IMPLIED>
<!ENTITY % atributoCoste "coste CDATA #IMPLIED"> 
<!ATTLIST precio %atributoCoste;>
<!ATTLIST oferta %atributoCoste;>
<!ENTITY infantil "Todas las edades.">

=== carlosdelval/EjerciciosLMSGI/Examenes resueltos/Examen01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoclub SYSTEM "Examen01.dtd">
<videoclub direccion="Calle la Patica" nombre="Sensacine" telefono="957591456">
  <peliculas>
    <pelicula codigo="ques" ingredientePrincipal="queso">
      <nombre>Insidious</nombre>
      <genero>Terror</genero>
      <precio coste="10" />
      <alquilada />
    </pelicula>
    <pelicula codigo="ench">
      <nombre>Hércules &infantil;</nombre>
      <genero>Fantasía</genero>
      <precio coste="20" />
      <disponible />
    </pelicula>
  </peliculas>
  <ofertas>
    <oferta coste="15">2x1 
      <peliculasReferidas codigoPelicula="ques" comboPeliculas="ques ench" />
    </oferta>
  </ofertas>
</videoclub>
