=== carlosdelval/EjerciciosLMSGI/Examen Lenguaje/examen-libreria.dtd
<!ELEMENT catalogo (libro*, oferta)>
<!ELEMENT libro (autor+, nombre, dedicatoria?, (disponible | agotado))>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dedicatoria EMPTY>
<!ELEMENT disponible EMPTY>
<!ELEMENT agotado EMPTY>
<!ATTLIST libro codigo ID #REQUIRED
                precio (20 | 10 | 15) "20"
                editorial CDATA #FIXED "Editorial La Mejor">
<!ELEMENT oferta (#PCDATA | combo)*>
<!ELEMENT combo ANY>
<!ATTLIST combo codigoLibro IDREF #REQUIRED
                codigoCombo IDREFS #IMPLIED>
<!ENTITY % atributoOferta "anuncio CDATA #IMPLIED">
<!ATTLIST oferta %atributoOferta;>
<!ATTLIST combo %atributoOferta;>
<!ENTITY marvel "Comic de superheroes">

=== carlosdelval/EjerciciosLMSGI/Examen Lenguaje/examen-libreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "examen-libreria.dtd">
<catalogo>
    <libro codigo="Harry" precio="20" editorial="Editorial La Mejor">
        <autor>JK Rowling</autor>
        <nombre>Harry Potter</nombre>
        <dedicatoria />
        <disponible />
    </libro>
    <libro codigo="Thor" precio="10" editorial="Editorial La Mejor">
        <autor>Marvel</autor>
        <nombre>Thor y el rayo</nombre>
        <disponible />
    </libro>
    <oferta anuncio="Llevate 2x1!">Oferta 2x1 en &marvel;
        <combo anuncio="Oferta en Potter y Thor!" codigoLibro="Harry" codigoCombo="Thor">
        </combo>
    </oferta>
</catalogo>
